apiVersion: v1
kind: ReplicationController
metadata:
  name: guestbookcontroller
spec:
  replicas: 1
  selector:
    app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: redis
        image: redis
      - name: guestbook
        image: google/guestbook-python-redis
        ports:
        - name: www
          containerPort: 80
        volumeMounts:
          - mountPath: /hosttmp
            name: data
      volumes:
        - name: data
          hostPath:
            path: /tmp
